import { Product } from "./product.types";

export const products: Product[] = [
  {
    id: "1",
    title: "Modern House",
    image: "/img/home.jpg",
    description: "Beautiful family house with a large garden.",
    price: 330000,
    rating: 4.9,
    reviews: 124,
    category: "Home",
  },
  {
    id: "2",
    title: "Beach Villa",
    image: "/img/beach.jpg",
    description: "Luxury villa near the sea.",
    price: 580000,
    rating: 4.8,
    reviews: 82,
    category: "Beach",
  },
  {
    id: "3",
    title: "BMW M4",
    image: "/img/car.jpg",
    description: "Sport coupe with premium interior.",
    price: 72000,
    rating: 4.9,
    reviews: 46,
    category: "Car",
  },
  {
    id: "4",
    title: "Italian Pizza",
    image: "/img/food.jpg",
    description: "Traditional pizza with mozzarella.",
    price: 18,
    rating: 4.7,
    reviews: 260,
    category: "Food",
  },
  {
    id: "5",
    title: "Mountain Cabin",
    image: "/img/home.jpg",
    description: "Cozy cabin surrounded by nature.",
    price: 210000,
    rating: 4.6,
    reviews: 39,
    category: "Home",
  },
  {
    id: "6",
    title: "Ocean Apartment",
    image: "/img/beach.jpg",
    description: "Apartment with an ocean view.",
    price: 290000,
    rating: 4.8,
    reviews: 67,
    category: "Beach",
  },
];