import { Product } from "./product.types";

export const products: Product[] = [
  {
    id: "1",
    title: "Modern House",
    images: ["/img/home.jpg", "/img/home2.jpg", "/img/home3.jpg"],
    description: "Beautiful family house with a large garden.",
    price: 330000,
    rating: 4.9,
    reviews: 124,
    categoryId: "home",
  },
  {
    id: "2",
    title: "Beach Villa",
    images: ["/img/beach.jpg"],
    description: "Luxury villa near the sea.",
    price: 580000,
    rating: 4.8,
    reviews: 82,
    categoryId: "beach",
  },
  {
    id: "3",
    title: "BMW M4",
    images: ["/img/car.jpg"],
    description: "Sport coupe with premium interior.",
    price: 72000,
    rating: 4.9,
    reviews: 46,
    categoryId: "car",
  },
  {
    id: "4",
    title: "Italian Pizza",
    images: ["/img/food.jpg"],
    description: "Traditional pizza with mozzarella.",
    price: 18,
    rating: 4.7,
    reviews: 260,
    categoryId: "food",
  },
  {
    id: "5",
    title: "Mountain Cabin",
    images: ["/img/home.jpg", "/img/home2.jpg", "/img/home3.jpg"],
    description: "Cozy cabin surrounded by nature.",
    price: 210000,
    rating: 4.6,
    reviews: 39,
    categoryId: "home",
  },
  {
    id: "6",
    title: "Ocean Apartment",
    images: ["/img/beach.jpg"],
    description: "Apartment with an ocean view.",
    price: 290000,
    rating: 4.8,
    reviews: 67,
    categoryId: "beach",
  },
];